[project]
name = "cags-classification"
version = "0.1.0"
description = "Top 3 (97.22% accuracy) deep learning image classifier on the CAGS (Cats and Dogs) 34-breed dataset using Vision Transformers, Two-Phase Fine-Tuning, Multi-Model Ensembling, and Test-Time Augmentation (TTA)."
authors = [
    { name = "Yannick Gibson" }
]
readme = "README.md"
license = { text = "CC-BY-SA-4.0" }
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "timm>=0.9.0",
    "torchmetrics>=1.0.0",
    "numpy>=1.24.0",
    "tensorboard>=2.14.0",
    "npfl138>=2526.5.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
